name: build

on: [push, pull_request]

env:
  UPSTREAM: tierconnect

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit, Integration and Acceptance Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #Login to docker
      -
        name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Download Migration Backup
        uses: actions/download-artifact@v4
        with:
          run-id: 14847275364
          repository: julio-rocha-coderoad-com/compose-project
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files in directory
        run: ls -R compose-data-backup

      - name: Extract Zip File
        run: unzip compose-data.zip

      - name: Uncompress compose-data
        run: tar -xvf compose-data.tar

